# 1.	Ipynbを新規作成する（ファイル名は　m03_自分の名前.ipynb　とする）。  
conda_python3のファイルを新規作成すればOK

# 2. CSVファイルをipynbと同じフォルダに配置し、データフレームを作成する。  
参考 3_2問題、3_3-machinelearning

In [1]:
# pandasをpdという名前でインポート
import pandas as pd

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [16]:
# CSVファイルを読み込みデータフレームを作成
df = pd.read_csv('income.csv')

# データフレームの先頭10行を表示 10行にしているのは、性別列が男性/女性の両方のデータを表示したいため
df.head(10)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K
0,67,Private,366425,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Male,99999,0,60,United-States,1
1,17,Private,244602,12th,8,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,0
2,31,Private,174201,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,1
3,58,State-gov,110199,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,0
4,25,State-gov,149248,Some-college,10,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States,0
5,59,State-gov,105363,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,0
6,70,Private,216390,9th,5,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,2653,0,40,United-States,0
7,35,Self-emp-not-inc,361888,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,60,Japan,0
8,28,Private,74784,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,50,United-States,0
9,28,Private,118089,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,4386,0,45,United-States,1

# 3.	行数、列数を表示する。  
参考 3_2-machinelearning

In [3]:
df.shape

(43957, 15)

# 4.	列名を取得する。  
参考 3_2-machinelearning

In [4]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income_>50K'],
      dtype='object')

# 5.	列のデータ型を取得する。  
参考 3_2-machinelearning

In [5]:
df.dtypes

age                 int64
workclass          object
fnlwgt              int64
education          object
educational-num     int64
marital-status     object
occupation         object
relationship       object
race               object
gender             object
capital-gain        int64
capital-loss        int64
hours-per-week      int64
native-country     object
income_>50K         int64
dtype: object

# 6.	データフレームの情報を表示する。  
参考 3_3-machinelearning

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43957 entries, 0 to 43956
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              43957 non-null  int64
 1   workclass        41459 non-null  object
 2   fnlwgt           43957 non-null  int64
 3   education        43957 non-null  object
 4   educational-num  43957 non-null  int64
 5   marital-status   43957 non-null  object
 6   occupation       41451 non-null  object
 7   relationship     43957 non-null  object
 8   race             43957 non-null  object
 9   gender           43957 non-null  object
 10  capital-gain     43957 non-null  int64
 11  capital-loss     43957 non-null  int64
 12  hours-per-week   43957 non-null  int64
 13  native-country   43194 non-null  object
 14  income_>50K      43957 non-null  int64
dtypes: int64(7), object(8)
memory usage: 5.0+ MB

# 7.	全ての列の統計量を表示する。  
参考 3_2-machinelearning

In [7]:
df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,income_>50K
count,43957.000000,4.395700e+04,43957.000000,43957.000000,43957.000000,43957.000000,43957.000000
mean,38.617149,1.896730e+05,10.074118,1093.559797,88.246491,40.407694,0.239279
std,13.734401,1.058215e+05,2.575092,7570.536063,404.588410,12.400303,0.426648
min,17.000000,1.349200e+04,1.000000,0.000000,0.000000,1.000000,0.000000
25%,28.000000,1.174960e+05,9.000000,0.000000,0.000000,40.000000,0.000000
50%,37.000000,1.781000e+05,10.000000,0.000000,0.000000,40.000000,0.000000
75%,48.000000,2.376710e+05,12.000000,0.000000,0.000000,45.000000,0.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000,1.000000

# 8.	gender列のデータ毎の出現回数を表示する。  
参考 3_2-machinelearning

In [9]:
# データフレームの特定の列を取り出す df['列名']
df['gender'].value_counts()

gender
Male      29400
Female    14557
Name: count, dtype: int64

# 9.	gender列をMaleは0、Femaleは1に変換する。  
参考 3_2-machinelearning

In [17]:
# 変換用の辞書を作る
gender_mapper = {'Male': 0, 'Female': 1}
# gender_mapper = {'Male': 0, 'Female': 1}

# データフレームから特定の列を取り出し、変換用の辞書で変換
# 変換結果は'gender_encoded'という列名でデータフレームに追加
df['gender_encoded'] = df['gender'].replace(gender_mapper)

# データフレームの先頭10行を表示
df.head(10)

/tmp/ipykernel_15686/2604732682.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender_encoded'] = df['gender'].replace(gender_mapper)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K,gender_encoded
0,67,Private,366425,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Male,99999,0,60,United-States,1,0
1,17,Private,244602,12th,8,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,0,0
2,31,Private,174201,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,1,0
3,58,State-gov,110199,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,0,0
4,25,State-gov,149248,Some-college,10,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States,0,0
5,59,State-gov,105363,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,0,0
6,70,Private,216390,9th,5,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,2653,0,40,United-States,0,1
7,35,Self-emp-not-inc,361888,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,60,Japan,0,0
8,28,Private,74784,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,50,United-States,0,0
9,28,Private,118089,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,4386,0,45,United-States,1,0

# 10.	race列をワンホットエンコーディングする。  
参考 3_3-machinelearning

In [18]:
# 'race'列のカテゴリカルデータをワンホットエンコーディングする
# columns:ワンホットエンコーディングをする列のリスト
# drop_first:True ワンホットエンコーディングした最初の列を削除する
df = pd.get_dummies(df, columns=['race'], drop_first=True,dtype=int)

# データフレームの先頭10行を表示
df.head(10)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K,gender_encoded,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,67,Private,366425,Doctorate,16,Divorced,Exec-managerial,Not-in-family,Male,99999,0,60,United-States,1,0,0,0,0,1
1,17,Private,244602,12th,8,Never-married,Other-service,Own-child,Male,0,0,15,United-States,0,0,0,0,0,1
2,31,Private,174201,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,40,United-States,1,0,0,0,0,1
3,58,State-gov,110199,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Male,0,0,40,United-States,0,0,0,0,0,1
4,25,State-gov,149248,Some-college,10,Never-married,Other-service,Not-in-family,Male,0,0,40,United-States,0,0,0,1,0,0
5,59,State-gov,105363,HS-grad,9,Never-married,Adm-clerical,Own-child,Male,0,0,40,United-States,0,0,0,0,0,1
6,70,Private,216390,9th,5,Married-civ-spouse,Machine-op-inspct,Wife,Female,2653,0,40,United-States,0,1,0,0,0,1
7,35,Self-emp-not-inc,361888,Bachelors,13,Married-civ-spouse,Sales,Husband,Male,0,0,60,Japan,0,0,0,0,0,1
8,28,Private,74784,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,Male,0,0,50,United-States,0,0,0,0,0,1
9,28,Private,118089,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Male,4386,0,45,United-States,1,0,0,0,0,1

# 11.	特徴量として、以下の列を使う。
* age
* fnlwgt
* educational-num
* raceをワンホットエンコーディングした結果の列
* genderをエンコーディングした結果の列

参考 データフレームから指定した列名のみを抽出(複数列の抽出) ... 3_3-machinelearning

In [19]:
# raceをワンホットエンコーディングした結果の列 → 'race_Asian-Pac-Islander','race_Black','race_Other','race_White'
# genderをエンコーディングした結果の列 → 'gender_encoded'
# モデルの学習に使うためには、目的変数(正解ラベル)の列も必要 → 'income_>50K'

# XGBoostの場合は先頭に目的変数(正解ラベル)、それ以降を特徴量とする
df_for_use = df[ ['income_>50K', 
                  'age', 'fnlwgt',
                  'educational-num',
                  'race_Asian-Pac-Islander',
                  'race_Black',
                  'race_Other',
                  'race_White',
                  'gender_encoded'] ].copy()

# モデルの学習で使うデータの先頭5行を表示
df_for_use.head()

,income_>50K,age,fnlwgt,educational-num,race_Asian-Pac-Islander,race_Black,race_Other,race_White,gender_encoded
0,1,67,366425,16,0,0,0,1,0
1,0,17,244602,8,0,0,0,1,0
2,1,31,174201,13,0,0,0,1,0
3,0,58,110199,4,0,0,0,1,0
4,0,25,149248,10,0,1,0,0,0

# 12.	データをトレーニング用、検証用、テスト用に分割する。  
トレーニング用：8割、検証用1割、テスト用：1割とする  
参考 3_4-machinelearning

In [20]:
# 機械学習用ライブラリのsklearnのmode_selectionモジュールからデータ分割関数のtrain_test_split関数をインポート
from sklearn.model_selection import train_test_split

In [21]:
# 分割1回目
# データセットを トレーニング用(train) と テスト＆検証用(train_and_validate) に分割する
# test_size:テスト＆検証用の割合 検証用1割とテスト用1割の合計なので2割(0.2)を指定
# random_state:乱数シード 任意の値でOK
# stratify:データフレームdf_for_useの目的変数(正解ラベル)の列のばらつき具合を維持して分割する
train, test_and_validate = train_test_split(df_for_use, test_size=0.2, random_state=42, stratify=df['income_>50K'])

In [22]:
# うまく分割できているか確認
# トレーニングデータセットの行数と列数を表示
print(train.shape)
# トレーニングデータセットの正解ラベルのデータの種類と件数を表示
print(train['income_>50K'].value_counts())

# テスト＆検証用データセットの行数と列数を表示
print(test_and_validate.shape)
# テスト＆検証用データセットの正解ラベルのデータの種類と件数を表示
print(test_and_validate['income_>50K'].value_counts())

(35165, 9)
income_>50K
0    26751
1     8414
Name: count, dtype: int64
(8792, 9)
income_>50K
0    6688
1    2104
Name: count, dtype: int64

In [23]:
# 分割2回目
# テスト&検証用データセットを テスト用(test) と 検証用(validate) に分割する
# test_size:半分ずつなので5割(0.5)を指定
# random_state:乱数シード 任意の値でOK
# stratify:データフレームtest_and_validateの目的変数(正解ラベル)の列のばらつき具合を維持して分割する
test, validate = train_test_split(test_and_validate, test_size=0.5, random_state=42, stratify=test_and_validate['income_>50K'])

In [24]:
# うまく分割できているか確認
# テストデータセットの行数と列数を表示
print(test.shape)
# テストデータセットの正解ラベルのデータの種類と件数を表示
print(test['income_>50K'].value_counts())

# 検証用データセットの行数と列数を表示
print(validate.shape)
# 検証用データセットの正解ラベルのデータの種類と件数を表示
print(validate['income_>50K'].value_counts())

(4396, 9)
income_>50K
0    3344
1    1052
Name: count, dtype: int64
(4396, 9)
income_>50K
0    3344
1    1052
Name: count, dtype: int64

## 分割したファイルをS3にアップロードする
参考 3_4-machinelearning

### アップロード関数の定義。また、バケット名やファイル名など、必要な情報を変数に定義しておく。

In [26]:
# 関数の中で「io」を使うため、importし忘れに注意。
import io

In [25]:
# S3バケットとプレフィックスの設定
#バケット名は必ずSandboxのものを使う
# prefixは任意でOK(コピペすればlab3)
bucket='c167743a4309710l10786217t1w968768184-sandboxbucket-n84ntgiwmhhw'
prefix='lab3'

# トレーニングデータ、テストデータ、検証データのファイル名設定 任意でOK
train_file='train.csv'
test_file='test.csv'
validate_file='validate.csv'

# osモジュールのインポート(ファイルパスの生成用)
import os

# S3へアクセスする準備
# boto3セッションからS3リソースを取得
import boto3
s3_resource = boto3.Session().resource('s3')

# S3にCSVファイルをアップロードするための関数を定義
def upload_s3_csv(filename, folder, dataframe):
    csv_buffer = io.StringIO()
    dataframe.to_csv(csv_buffer, header=False, index=False)
    # ★ 以下の部分でS3にデータ(dataframeの内容)をアップしている
    s3_resource.Bucket(bucket).Object(os.path.join(prefix, folder, filename)).put(Body=csv_buffer.getvalue())

### 定義した関数を使って、先ほど分割した3つのデータフレームをアップロードする。

In [27]:
# DataFrameをS3にアップロードする upload_s3_csv関数を使用

# ファイル名:train_fileの値
# フォルダ名:'train'
# アップするデータ:train(DataFrame)の内容
upload_s3_csv(train_file, 'train', train)

# ファイル名:test_fileの値
# フォルダ名:'test'
# アップするデータ:test(DataFrame)の内容
upload_s3_csv(test_file, 'test', test)

# ファイル名:validate_fileの値
# フォルダ名:'validate'
# アップするデータ:validate(DataFrame)の内容
upload_s3_csv(validate_file, 'validate', validate)

# 13.	XGBoostのモデルを作成する。  
参考 3_4-machinelearning

## XGBoostのDockerコンテナを取得 (変数containerに格納しておく)

In [28]:
# Amazon SageMaker用のモジュールをインポート
import boto3
from sagemaker.image_uris import retrieve

# SageMakerにおいてXGBoostアルゴリズムを利用するためのDockerコンテナイメージを取得
container = retrieve('xgboost',boto3.Session().region_name,'1.0-1')

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/ec2-user/.config/sagemaker/config.yaml

## ハイパーパラメータの設定を決める (変数hyperparamsに格納しておく)

In [23]:
# XGBoostのハイパーパラメータを辞書で保持
# num_round: 学習回数 大きすぎると過学習、小さすぎると学習不足
# eval_metric:モデルの評価指標 'auc'...ROC曲線の面積 0～1の範囲で1に近いほど分類性能が高い
# objective:目的関数(この関数の計算結果を最小/最大にするように学習する) 'binary:logistic'...2クラス分類のための関数
hyperparams={"num_round":"42",
             "eval_metric": "auc",
             "objective": "binary:logistic"}

## モデルのオブジェクトを作成 (変数xgb_modelに格納しておく)
containerとhyperparamsが必要

In [24]:
# SageMaker SDKを使用して、XGBoostのモデルをトレーニングおよびデプロイするために必要なモジュールをインポート
import sagemaker

# トレーニング結果を保存するS3のパス
s3_output_location="s3://{}/{}/output/".format(bucket, prefix)

# SageMakerのXGBoostアルゴリズムを使用するためにXGBoost Estimatorを作成
# image_uri:使用するコンテナ
# role:SageMakerの実行ロール sagemaker.get_execution_role()で取得した値
# instance_count:トレーニングに使用するインスタンスの数
# instance_type:トレーニングに使用するインスタンスのタイプ
# output_path: トレーニング結果を保存するパス
# hyperparameters: ハイパーパラメータ
# sagemaker_session: SageMakerのセッション sagemaker.session()で取得した値
xgb_model=sagemaker.estimator.Estimator(image_uri=container,
                                       role=sagemaker.get_execution_role(),
                                       instance_count=1,
                                       instance_type='ml.m4.xlarge',
                                       output_path=s3_output_location,
                                        hyperparameters=hyperparams,
                                        sagemaker_session=sagemaker.Session())

                    INFO     Found credentials from IAM Role:                                   ]8;id=519464;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=827316;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/botocore/credentials.py#1075\1075]8;;\
                             BaseNotebookInstanceEc2InstanceRole

                    INFO     Found credentials from IAM Role:                                   ]8;id=738119;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=47904;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/botocore/credentials.py#1075\1075]8;;\
                             BaseNotebookInstanceEc2InstanceRole

                    INFO     Found credentials from IAM Role:                                   ]8;id=205114;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=691288;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/botocore/credentials.py#1075\1075]8;;\
                             BaseNotebookInstanceEc2InstanceRole

## モデルに学習させるデータを設定 (変数data_channelsに格納)

In [25]:
# SageMakerのトレーニングジョブに使用するトレーニングデータのパスとファイルの種類'text/csv'を指定

# トレーニング用データオブジェクトを作る (S3から指定したCSVを読み込む)
train_channel = sagemaker.inputs.TrainingInput(
    "s3://{}/{}/train/".format(bucket, prefix, train_file), # パス(～/train/～)は、S3にアップする時に設定していたもの
    content_type='text/csv')

# 検証用データオブジェクトを作る (S3から指定したCSVを読み込む)
validate_channel = sagemaker.inputs.TrainingInput(
    "s3://{}/{}/validate/".format(bucket, prefix, validate_file), # パス(～/validate/～)は、S3にアップする時に設定していたもの
    content_type='text/csv')

# トレーニングジョブで使うデータを辞書型で保持しておく（学習の時にこれで指定する）
# キー'train'にトレーニング用データオブジェクト、キー'validation'に検証用データオブジェクト を指定
data_channels = {'train': train_channel, 'validation': validate_channel}

## 学習開始 fit!!
data_channelsが必要

In [26]:
xgb_model.fit(inputs=data_channels, logs=False)

[02/20/25 09:10:06] INFO     SageMaker Python SDK will collect telemetry to help us better  ]8;id=172952;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/telemetry/telemetry_logging.py\telemetry_logging.py]8;;\:]8;id=634016;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/telemetry/telemetry_logging.py#91\91]8;;\
                             understand our user's needs, diagnose issues, and deliver
                             additional features.
                             To opt out of telemetry, please disable via TelemetryOptOut
                             parameter in SDK defaults config. For more information, refer
                             to
                             https://sagemaker.readthedocs.io/en/stable/overview.html#confi
                             guring-and-using-defaults-with-the-sagemaker-python-sdk.

                    INFO     Creating training-job with name:                                       ]8;id=89131;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py\session.py]8;;\:]8;id=151092;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py#1042\1042]8;;\
                             sagemaker-xgboost-2025-02-20-09-10-06-144

2025-02-20 09:10:06 Starting - Starting the training job.....
2025-02-20 09:10:37 Starting - Preparing the instances for training.....
2025-02-20 09:11:10 Downloading - Downloading input data.....
2025-02-20 09:11:40 Downloading - Downloading the training image...........
2025-02-20 09:12:41 Training - Training image download completed. Training in progress....
2025-02-20 09:13:01 Uploading - Uploading generated training model..
2025-02-20 09:13:14 Completed - Training job completed

# 14.	テスト用データの1行目を用いて、リアルタイム推論をする。  
参考 3_5-machinelearning

## モデルのホスティング=エンドポイントを作成 (エンドポイントを変数xgb_predictorに格納)

In [27]:
# ★ リアルタイム推論
# XGBoostモデルをデプロイしてエンドポイントを作成
# xgb_model.fit()が済んでいるモデルに対してdeployメソッドを呼び出し、エンドポイントを取得
xgb_predictor = xgb_model.deploy(initial_instance_count=1, # インスタンスの数を指定
                serializer = sagemaker.serializers.CSVSerializer(), # シリアライザをCSV形式に設定
                instance_type='ml.m4.xlarge') # インスタンスタイプを指定

[02/20/25 09:15:23] INFO     Creating model with name: sagemaker-xgboost-2025-02-20-09-15-23-807    ]8;id=717831;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py\session.py]8;;\:]8;id=314479;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py#4094\4094]8;;\

[02/20/25 09:15:24] INFO     Creating endpoint-config with name                                     ]8;id=98137;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py\session.py]8;;\:]8;id=139018;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py#5889\5889]8;;\
                             sagemaker-xgboost-2025-02-20-09-15-23-807

                    INFO     Creating endpoint with name sagemaker-xgboost-2025-02-20-09-15-23-807  ]8;id=534529;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py\session.py]8;;\:]8;id=494630;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py#4711\4711]8;;\

--------!

## リアルタイム推論させるデータを作成 (変数test_rowに格納)

In [28]:
# 再確認としてテスト用データ(test)の中身を見てみる
test.head()

# このデータの1行目 かつ age列より後ろの列を、推論用のデータとして用いたい
# ※推論させるときは特徴量のみ使う。正解ラベルは渡さない。

,income_>50K,age,fnlwgt,educational-num,race_Asian-Pac-Islander,race_Black,race_Other,race_White,gender_encoded
40353,0,28,246974,9,0,0,0,1,0
36339,1,46,27802,12,0,0,0,1,0
18170,0,41,575442,10,0,0,0,1,0
28637,1,43,261929,16,0,0,0,1,0
5172,0,21,455361,5,0,0,0,1,0

In [29]:
# ilocを使い、行インデックス0の行かつ、列インデックス1～末尾のデータを抽出する
row = test.iloc[0:1,1:] # テストデータから行インデックス0で、列インデックス1以降のデータを取得

# 抽出した結果を表示
row.head()

,age,fnlwgt,educational-num,race_Asian-Pac-Islander,race_Black,race_Other,race_White,gender_encoded
40353,28,246974,9,0,0,0,1,0

In [30]:
# rowのデータを カンマ区切り値の文字列 にする
batch_X_csv_buffer = io.StringIO()
row.to_csv(batch_X_csv_buffer, header=False, index=False)
test_row = batch_X_csv_buffer.getvalue()

# 変換した文字列を表示
print(test_row)

28,246974,9,0,0,0,1,0

## リアルタイム推論を実行

In [31]:
# ★ モデルに予測させる エンドポイント.predictメソッド
xgb_predictor.predict(test_row)

# 予測した結果、1である確率が表示される

b'0.09101827442646027'

今回実行したときの結果は0.09  
1である確率は9% → 0である可能性が高い  
testの先頭5行を表示したとき、1行目の正解は0であったので、正しく推論できている

In [32]:
# 本来はエンドポイントを削除しなければ課金され続ける
# xgb_predictor.delete_endpoint(delete_endpoint_config=True)

# 15.	テスト用データでバッチ推論をする。  
参考 3_5-machinelearning

## バッチ推論させるデータを作成 (S3に保存)

In [33]:
# ★ バッチ推論用に 全レコードの正解列以外を抽出
batch_X = test.iloc[:,1:]; # テストデータから全ての行の列インデックス1以降のデータを取得

# 取得したデータの最初の5行を表示
batch_X.head()

,age,fnlwgt,educational-num,race_Asian-Pac-Islander,race_Black,race_Other,race_White,gender_encoded
40353,28,246974,9,0,0,0,1,0
36339,46,27802,12,0,0,0,1,0
18170,41,575442,10,0,0,0,1,0
28637,43,261929,16,0,0,0,1,0
5172,21,455361,5,0,0,0,1,0

In [34]:
# ★ 抽出したDataFrameをS3にアップロード

# バッチ推論で予測させるデータのファイル名
batch_X_file='batch-in.csv'

# S3にアップロード
upload_s3_csv(batch_X_file, 'batch-in', batch_X)

## バッチ推論を実行(バッチジョブを実行)

In [35]:
# バッチ推論で予測した結果の出力先を指定
batch_output = "s3://{}/{}/batch-out/".format(bucket,prefix)

# バッチ推論で予測させるデータのフルパス
batch_input = "s3://{}/{}/batch-in/{}".format(bucket,prefix,batch_X_file)

# ★ XGBoostトランスフォーマー(変換処理をしてくれるオブジェクト)を作成
# instance_count: トランスフォーマーの実行に使用するインスタンスの数
# instance_type: トランスフォーマーのインスタンスのタイプ
# strategy: バッチ変換のストラテジーを指定（MultiRecordは複数の入力レコードに対応）
# assemble_with: バッチ変換の際に結果をどのようにまとめるか指定（Lineは行ごとにまとめる）
# output_path: バッチ変換の結果を保存するS3のパスを指定
xgb_transformer = xgb_model.transformer(instance_count=1,
                                       instance_type='ml.m4.xlarge',
                                       strategy='MultiRecord',
                                       assemble_with='Line',
                                       output_path=batch_output)

# ★ バッチ変換(transform)を実行
# data: 変換対象のデータのパスを指定
# data_type: 変換対象のデータのタイプを指定（S3PrefixはS3上のプレフィックス内のデータを指定）
# content_type: 変換対象データのコンテンツタイプを指定
# split_type: 入力データをどのように分割するか指定（Lineは行ごとに分割）
xgb_transformer.transform(data=batch_input,
                         data_type='S3Prefix',
                         content_type='text/csv',
                         split_type='Line')

# バッチ変換が完了するのを待機
xgb_transformer.wait()

[02/20/25 09:19:56] INFO     Creating model with name: sagemaker-xgboost-2025-02-20-09-19-56-310    ]8;id=623371;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py\session.py]8;;\:]8;id=732029;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py#4094\4094]8;;\

                    INFO     Creating transform job with name:                                      ]8;id=787094;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py\session.py]8;;\:]8;id=586994;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py#3951\3951]8;;\
                             sagemaker-xgboost-2025-02-20-09-19-56-942

....................................
...

## バッチ推論の結果データを取得(S3からダウンロードし、変数target_predictedに格納)

In [36]:
# boto3モジュールを使用してS3クライアントを作成
s3 = boto3.client('s3')

# S3バケットからオブジェクトを取得
obj = s3.get_object(Bucket=bucket, Key="{}/batch-out/{}".format(prefix,'batch-in.csv.out'))

# バッチ変換の結果として得られた予測結果を読み込む
# ここではCSVデータを読み込み、列名を'class'としてDataFrameに変換
target_predicted = pd.read_csv(io.BytesIO(obj['Body'].read()),sep=',',names=['class'])

# DataFrameの最初の5行を表示
target_predicted.head(5)

[02/20/25 09:26:30] INFO     Skipping checksum validation. Response did not contain one of the  ]8;id=136109;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/botocore/httpchecksum.py\httpchecksum.py]8;;\:]8;id=560590;file:///home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/botocore/httpchecksum.py#481\481]8;;\
                             following algorithms: ['crc32', 'sha1', 'sha256'].

      class
0  0.091018
1  0.373154
2  0.606170
3  0.723769
4  0.011766

今回実行したときの結果、1である確率は、上から 9%、37%、60%、72%、1%…  
上から3つめや4つめレコードの予測結果を1とするか、閾値を決めていかなければならない

# 16.	予測結果を二値変換する関数（閾値で0か1かに振り分ける）を作る。変換の閾値は0.65とする。  
参考 3_6-machinelearning

In [37]:
# 予測結果の確率を受け取り、最終的に1か0かを決める関数を定義
# 確率が閾値より大きい場合は1、それ以外は0に変換して返す
def binary_convert(x):
    threshold = 0.65 # 閾値
    if x > threshold:
        return 1
    else:
        return 0

## 17.	バッチ推論した結果を上記関数で二値変換し、結果を表示する。また、実際の正解値も表示し、比較できるようにする。
参考 3_7-machinelearning

In [38]:
# 'class'列の各要素に関数を適用し、結果を変数target_predictd_binaryに代入する(予測結果のリスト)
target_predicted_binary = target_predicted['class'].apply(binary_convert)

# 予測結果を表示 1:異常 0:正常
print(target_predicted_binary.head(5))

0    0
1    0
2    0
3    1
4    0
Name: class, dtype: int64

閾値を65%にしたので、上から4つめの予測結果は1となった

In [39]:
# テストデータ(正解が分かっている)を表示
test.head(5)

,income_>50K,age,fnlwgt,educational-num,race_Asian-Pac-Islander,race_Black,race_Other,race_White,gender_encoded
40353,0,28,246974,9,0,0,0,1,0
36339,1,46,27802,12,0,0,0,1,0
18170,0,41,575442,10,0,0,0,1,0
28637,1,43,261929,16,0,0,0,1,0
5172,0,21,455361,5,0,0,0,1,0

正解をみると上から2つ目も本来は1なので、推論結果が間違いであることがわかる